pipeline {
    agent any
    stages {        
        stage('Build') {
            steps {
                bat "mvn clean install -f spring-boot-war-deployment-example/pom.xml"
            }
        }
        stage('Test'){
        	steps {
        		bat "mvn test -f spring-boot-war-deployment-example/"
        	}
        }
        stage('Package'){
        	steps {
        		bat "mvn package -f spring-boot-war-deployment-example/"
        	}
        }
        stage('Deploy') {
            steps {
            	echo "Deploying........"
                bat 'copy "C:\\Program Files (x86)\\Jenkins\\workspace\\springbootapp\\spring-boot-war-deployment-example\\target\\"  "C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\"' 
            }
        }
        
    }
}
