pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat "mvn clean install -f cicdpipelineapp/pom.xml"
            }
        }
        stage('Test'){
        	steps {
        		bat "mvn test -f cicdpipelineapp/"
        	}
        }
        stage('Package'){
        	steps {
        		bat "mvn package -f cicdpipelineapp/"
        	}
        }
        stage('Deploy') {
            steps {
            	echo "Deploying........"
                bat 'xcopy "C:\\Program Files (x86)\\Jenkins\\workspace\\cicd-pipeline-stages\\cicdpipelineapp\\target\\"  "C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\"' 
            }
        }
        
    }
}
